### ISSUE TITLE
Add support for GHC 7.10

### ISSUE THREAD

**Issue by juanpaucar** [begriffs/heroku-buildpack-ghc#74]
Hi Everyone,
I was wondering if maybe it's time to use `GHC 7.10.1` or `GHC 7.10.2` and a newer version of Cabal. I'm wondering this since GHC 7.10 has a new version `7.10.2` which should solve the minor issues on the 7.10.1 version. Is there any reason that keeps us from using GHC 7.10.2 or are we even able to give the choice to the user?

Thanks,
Warm Regards

**Comment by mseri** [comment]
+1

**Comment by begriffs** [comment]
Didn't realize people are still using this buildpack! I'll add a todo for myself to update it for you.

**Comment by mseri** [comment]
Thanks!

Sometimes when you need to spin something fast it's very useful, but having to recompile 7.10 and cabal is annoying :P

**Comment by begriffs** [comment]
K, it uses newer GHC and Cabal and I also cached the binaries on S3 for it.

**Comment by mseri** [comment]
Wow, thank you very much!!!
